[package]
edition = "2024"
name = "network"
version = "0.1.0"
authors = ["Niklas Sombert <niklas.sombert@uni-duesseldorf.de"]

[lib]
test = false
doctest = false
bench = false

[dependencies]
syscall = { path = "../syscall" }
